version: '3.3'
services:
  mgallery-postgres:
    image: postgres:9.6
    container_name: mgallery-postgres
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=mgallery
      - POSTGRES_USER=mgallery
      - POSTGRES_PASSWORD=pa55word
  mgallery-redis:
    image: redis:latest
    container_name: mgallery-redis
  mgallery-app:
    image: mantiby/mgallery:latest
    container_name: mgallery-app
    ports:
      - "8888:8888"
      - "5555:5555"
    links:
      - mgallery-postgres
      - mgallery-redis
    volumes:
      - ../:/srv/mgallery/
      - ../../log/:/var/log/mgallery/
    environment:
      - DATABASE_URL=postgresql://mgallery:pa55word@mgallery-postgres/mgallery