version: '3.3'
services:

  mgallery-postgres:
    image: postgres:latest
    container_name: mgallery-postgres
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=mgallery
      - POSTGRES_USER=mgallery
      - POSTGRES_PASSWORD=pa55word
    ports:
      - "5432:5432"

  mgallery-redis:
    image: redis:latest
    container_name: mgallery-redis

  mgallery-app:
    image: mantiby/mgallery:latest
    container_name: mgallery-app
    ports:
      - "8000:8000"
      - "5555:5555"
    links:
      - mgallery-postgres
      - mgallery-redis
    volumes:
      - ../:/srv/mgallery/
      - ../../log/:/var/log/mgallery/
      - ../../lib/:/var/lib/mgallery/