version: '3.3'
services:

  mgallery-postgres:
    image: postgres:latest
    container_name: mgallery-postgres
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=mgallery
      - POSTGRES_USER=mgallery
      - POSTGRES_PASSWORD=pa55word
    ports:
      - 5432:5432

  mgallery-redis:
    image: redis:latest
    container_name: mgallery-redis

  mgallery-app:
    image: mantiby/mgallery:latest
    container_name: mgallery-app
    ports:
      - 8808:8808
    links:
      - mgallery-postgres
      - mgallery-redis
    volumes:
      - ../:/srv/mgallery/
      - /home/manti/www/manti/mgallery/log/:/var/log/mgallery/
      - /home/manti/www/manti/mgallery/lib/:/var/lib/mgallery/
    environment:
      - FLASK_DEBUG=1
      - TEMPLATES_AUTO_RELOAD=1
      - FLOWER_URL=http://localhost/flower/
      - ROLE=app

  mgallery-celery:
    image: mantiby/mgallery:latest
    container_name: mgallery-celery
    links:
      - mgallery-postgres
      - mgallery-redis
    volumes:
      - ../:/srv/mgallery/
      - /home/manti/www/manti/mgallery/log/:/var/log/mgallery/
      - /home/manti/www/manti/mgallery/lib/:/var/lib/mgallery/
    environment:
      - ROLE=celery

  mgallery-flower:
    image: mantiby/mgallery:latest
    container_name: mgallery-flower
    ports:
      - 5505:5505
    links:
      - mgallery-postgres
      - mgallery-redis
    volumes:
      - ../:/srv/mgallery/
      - /home/manti/www/manti/mgallery/log/:/var/log/mgallery/
    environment:
      - ROLE=flower