version: '3.3'
services:
  mgallery-postgres:
    image: postgres:9.6
    container_name: mgallery-postgres
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 12G
        reservations:
          cpus: '0.5'
          memory: 8G
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=mgallery
      - POSTGRES_USER=mgallery
      - POSTGRES_PASSWORD=pa55word
  mgallery-postgres-test:
    image: postgres:9.6
    container_name: mgallery-postgres-test
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=mgallery
      - POSTGRES_USER=mgallery
      - POSTGRES_PASSWORD=pa55word
  mgallery-redis:
    image: redis:latest
    container_name: mgallery-redis
  mgallery-app:
    image: mantiby/mgallery:latest
    container_name: mgallery-app
    ports:
      - "8000:8000"
      - "5555:5555"
    links:
      - mgallery-postgres
      - mgallery-postgres-test
      - mgallery-redis
    volumes:
      - ../:/srv/mgallery/
      - ../../log/:/var/log/mgallery/
      - /media/manti/Backup2/Photo/Library:/gallery
    environment:
      - GALLERY_PATH=/gallery
      - DATABASE_URL=postgresql://mgallery:pa55word@mgallery-postgres/mgallery
      - TEST_DATABASE_URL=postgresql://mgallery:pa55word@mgallery-postgres-test/mgallery