name: Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    name: Run checks

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        shell: bash
        run: |
          uv sync --locked --all-extras --dev

      - name: Run pre-commit hooks
        run: |
          uv run ty check
          uv run pre-commit run
